version: '3'

services:
  ws1:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./ws1:/var/www/public:z
      - ./nginx:/etc/nginx/conf.d:z
    restart: unless-stopped
    ports:
      - "$FIRST_PORT:80"
    container_name: ws1
    networks:
      network:
        ipv4_address: $FIRST_HOST

  ws2:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./ws2:/var/www/public:z
      - ./nginx:/etc/nginx/conf.d:z
    restart: unless-stopped
    ports:
      - "$SECND_PORT:80"
    container_name: ws2
    networks:
      network:
        ipv4_address: $SECND_HOST

  ws3:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./ws3:/var/www/public:z
      - ./nginx:/etc/nginx/conf.d:z
    restart: unless-stopped
    ports:
      - "$THIRD_PORT:80"
    container_name: ws3
    networks:
      network:
        ipv4_address: $THIRD_HOST

  blc:
    image: haproxy:lts-alpine
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    restart: unless-stopped
    ports:
      - "$BLNCR_PORT:80"
    container_name: blc
    networks:
      network:
        ipv4_address: $BLNCR_HOST

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: $NETWK_ADDR
          gateway: $NETWK_GATE
